on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

name: test-coverage

jobs:
  test-coverage:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.3'
      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages("remotes",dependencies=TRUE)
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)

        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-3.6-${{ hashFiles('depends.Rds') }}
          restore-keys: macOS-r-3.6-


      - name: Install dependencies
        run:  |
              install.packages("remotes", dependencies=TRUE)
              remotes::install_deps(dependencies = TRUE)
              remotes::install_github("tidyverse/dplyr")

        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
