on: [push, pull_request]

name: R-CMD-check-devel

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.0.1'
      - name: Install make tools
        run: brew install automake
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"), dependencies=TRUE)
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("tidyverse/dplyr")
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
